# Generated by Django 4.0.4 on 2022-07-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default_acc.jpeg', null=True, upload_to='avatar/%Y/%m/%d'),
        ),
    ]
